# Generated by Django 5.1.1 on 2024-09-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
